language: cpp
compiler:
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev automake

script: 
  - cd QuantLib
  - sh ./autogen.sh
  - ./configure
  - make

notifications:
  email: false
